services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=ai-meter-db'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '60716:5432'
    container_name: 'ai-meter-db'