server:
  error:
    include-stacktrace: always

spring:
  docker:
    compose:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:60716/ai-meter-db
    username: myuser
    password: secret

  jpa:
    show-sql: true
    properties:
      hibernate:
        format.sql: true

logging:
  config: classpath:logging/log4j-dev.yaml